#
# Set these to the appropriate value.
#
DIM          = 3

COMP         = g++

DEBUG        = FALSE

USE_MPI      = FALSE

USE_OMP      = TRUE

AMREX_HOME = ../../..
include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package

include $(AMREX_HOME)/Src/Base/Make.package
include $(AMREX_HOME)/Src/GeometryShop/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules

