AMREX_HOME  ?= ../../../amrex
PICSAR_HOME ?= ../../../picsar

DEBUG    = FALSE

DIM    = 2
DIM    = 3

COMP    = gcc

TINY_PROFILE = TRUE
TINY_PROFILE = FALSE

USE_OMP   = TRUE

EBASE     = main

USE_PYTHON_MAIN = FALSE

USE_PSATD = FALSE

WARPX_HOME := ../../../warpx
include $(WARPX_HOME)/Source/Make.WarpX
