AMREX_HOME = ../../..

DEBUG	= FALSE
DIM	= 3
COMP    = gcc

USE_MPI   = FALSE
USE_OMP   = TRUE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
