AMREX_HOME = ../../..

DEBUG     = FALSE
DEBUG     = TRUE

USE_MPI   = TRUE

USE_OMP   = FALSE

PROFILE   = FALSE
COMM_PROFILE  = FALSE
TRACE_PROFILE = FALSE

COMP      = g++
DIM       = 3
PRECISION = DOUBLE

EBASE     = BcastClasses

CEXE_sources += BcastClasses.cpp

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules

