BOXLIB_HOME = ../../..

DEBUG     = FALSE
DEBUG     = TRUE

USE_MPI   = TRUE

USE_OMP   = FALSE

PROFILE   = FALSE
COMM_PROFILE  = FALSE
TRACE_PROFILE = FALSE

COMP      = g++
FCOMP     = gfortran
DIM       = 3
PRECISION = DOUBLE

EBASE     = BcastClasses

CEXE_sources += BcastClasses.cpp

include $(BOXLIB_HOME)/Tools/C_mk/Make.defs

include $(BOXLIB_HOME)/Src/C_BaseLib/Make.package

include $(BOXLIB_HOME)/Tools/C_mk/Make.rules

