AMREX_HOME ?= ../../../../..

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 3

COMP    = pgi

TINY_PROFILE  = TRUE
USE_PARTICLES = TRUE

PRECISION     = DOUBLE

USE_MPI       = TRUE
USE_OMP       = FALSE
USE_ACC       = FALSE
USE_CUDA      = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ../../Make.EMPIC
