AMREX_HOME = ../../..

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 2

COMP    = gcc

USE_MPI   = FALSE
USE_OMP   = FALSE
USE_CUDA  = TRUE
USE_HIP   = FALSE
USE_DPCPP = FALSE

TINY_PROFILE = TRUE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
