AMREX_HOME ?= ../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

USE_PARTICLES = TRUE

DIM        = 2
#DIM       = 3

COMP	   = g++

USE_MPI    = TRUE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
