AMREX_HOME = ../../../

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 3

COMP    = gcc

TINY_PROFILE = FALSE

PRECISION = DOUBLE

USE_MPI   = FALSE
USE_OMP   = FALSE

###################################################

EBASE     = main

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
