build:

  pre_ci:
    docker build -no-cache -t warpx:tip .

  pre_ci_boot:
    image_name: warpx
    image_tag: tip

  ci:
    - cd /home/regression_testing
    - export FFTW_HOME=/usr/
    - python regtest.py ../rt-WarpX/WarpX-tests.ini --no_update all --make_benchmarks 'Benchmarking'
