AMREX_HOME = ../../../

DEBUG	= FALSE

DIM	= 3

COMP    = gcc

USE_CUDA  = TRUE

USE_MPI   = FALSE
USE_OMP   = FALSE

USE_KERNEL_TIMER = TRUE
TINY_PROFILE = TRUE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
