AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

#DIM        = 2
DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = TRUE

USE_SENSEI_INSITU = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
