# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?= ../../../../../

DIM       = 3

DEBUG     = FALSE
USE_MPI   = TRUE
USE_OMP   = FALSE
USE_CUDA  = TRUE

COMP      = ibm
USE_OMP_OFFLOAD = TRUE

Bpack   := ./Make.package
Blocs   := .

include ../../Make.HEAT
