AMREX_HOME ?= ../../../../..
USE_EB = FALSE
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE
DEBUG      = TRUE


DIM       = 3
DIM        = 2
COMP	   = gnu

#USE_PARTICLES = TRUE

USE_MPI    = TRUE
USE_MPI    = FALSE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv.Diff
