AMREX_HOME ?= ../../

DEBUG	= FALSE

DIM	= 3

COMP    = pgi

USE_CUDA = TRUE
USE_MPI   = TRUE
USE_OMP   = FALSE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
