#!/bin/bash

if [ "$#" -ne 3 ]
then
  echo " " 
  echo " Generate a release tarball: "
  echo " " 
  echo "        $0 <n1.n2.n3> (where n1.n2.n3 is a version string)"
  echo " " 
  echo "        Note that "vn1.n2.n3" must be a named tag in the git repository"
  echo "        Done with the following sequence: "
  echo "          #> git tag -a v\${version} -m \"Version \${version}\""
  echo "          #> git push --tags" 
  echo " " 
fi

export version=$1.$2.$3
export outfile="../ccse-${version}.tar.gz"
echo "Creating tarball ${outfile} and Tools/CMake/BoxLib_Version.cmake" 
git archive --format=tar --prefix=ccse-${version}/ v${version} | gzip >${outfile}

cat <<EOF > Tools/CMake/BoxLib_Version.cmake
# Write the CCSEConfig.cmake file, can set as many as the following
# VERSION       = full requested version string
# VERSION_MAJOR = major version if requested, else 0
# VERSION_MINOR = minor version if requested, else 0
# VERSION_PATCH = patch version if requested, else 0
# VERSION_TWEAK = tweak version if requested, else 0
# VERSION_COUNT = number of version components, 0 to 4
SET(CCSE_VERSION       ${version})
SET(CCSE_VERSION_MAJOR $1)
SET(CCSE_VERSION_MINOR $2)
SET(CCSE_VERSION_PATCH $3)
SET(CCSE_VERSION_COUNT 3)
EOF

