#!/usr/bin/env bash

# create a file buildInfo.cpp with various functions returning build
# information.
#
# arguments:
#
#   boxlib directory
#   C++ compiler
#   Fortran compiler
#   auxillary data 1
#   auxillary data 2
#
# here the auxillary data is any string -- different codes may have
# different needs.

if [ -z "IN_BASH" ]; then
  export IN_BASH=1
  exec bash -f "$0" "$@"
fi

# the basic build strings will be MAX_STRING_LENGTH long
MAX_STRING_LENGTH=128

rm -f build_info.f90

BUILD_DATE=`date | cut -c 1-$MAX_STRING_LENGTH`
BUILD_DIR=`pwd | cut -c 1-$MAX_STRING_LENGTH`
BUILD_MACHINE=`uname -a | cut -c 1-$MAX_STRING_LENGTH`

BOXLIB_DIR=`echo $1 | cut -c 1-$MAX_STRING_LENGTH`
shift

COMP=`echo $1 | cut -c 1-$MAX_STRING_LENGTH`
shift

FCOMP=`echo $1 | cut -c 1-$MAX_STRING_LENGTH`
shift

naux=0
ngit=0
while [ $# -gt 0 ] ; do
  INFOTYPE=`echo $1 | cut -c 1-3`
  INFOPATH=`echo $1 | cut -c 5-$MAX_STRING_LENGTH`
  if [ "$INFOTYPE" = "AUX" ] ; then
      naux=$((naux+1))
      AUX[$naux]="$INFOPATH"
  elif [ "$INFOTYPE" = "GIT" ] ; then
      ngit=$((ngit+1))
      if [ -d "$INFOPATH" ] ; then
	  GIT[$ngit]=`cd "$INFOPATH"; git rev-parse HEAD | cut -c 1-$MAX_STRING_LENGTH`
      fi
  fi

  shift
done


cat > buildInfo.cpp << EOF

const char* buildInfoGetBuildDate() {

  static const char BUILD_DATE[] = "$BUILD_DATE";
  return BUILD_DATE;
}

const char* buildInfoGetBuildDir() {

  static const char BUILD_DIR[] = "$BUILD_DIR";
  return BUILD_DIR;
}

const char* buildInfoGetBuildMachine() {

  static const char BUILD_MACHINE[] = "$BUILD_MACHINE";
  return BUILD_MACHINE;
}

const char* buildInfoGetBoxlibDir() {

  static const char BOXLIB_DIR[] = "$BOXLIB_DIR";
  return BOXLIB_DIR;
}

const char* buildInfoGetComp() {

  static const char COMP[] = "$COMP";
  return COMP;
}

const char* buildInfoGetFcomp() {

  static const char FCOMP[] = "$FCOMP";
  return FCOMP;
}

const char* buildInfoGetAux(int i) {

  static const char AUX1[] = "${AUX[1]}";
  static const char AUX2[] = "${AUX[2]}";
  static const char AUX3[] = "${AUX[3]}";
  static const char EMPT[] = "";

  switch(i)
  {
    case 1: return AUX1;
    case 2: return AUX2;
    case 3: return AUX3;
    default: return EMPT;
  }
}

const char* buildInfoGetGitHash(int i) {

  static const char HASH1[] = "${GIT[1]}";
  static const char HASH2[] = "${GIT[2]}";
  static const char HASH3[] = "${GIT[3]}";
  static const char EMPT[] = "";

  switch(i)
  {
    case 1: return HASH1;
    case 2: return HASH2;
    case 3: return HASH3;
    default: return EMPT;
  }
}

EOF
