AMREX_HOME ?= ../../../

USE_MPI      = FALSE
USE_OMP      = FALSE
TINY_PROFILE = FALSE
DIM          = 3

USE_CUDA = TRUE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
