#!/bin/sh

BLNPY=$1
shift 1

echo python module pyfboxlib
echo interface

for i in $*; do
    cat $i
done

echo end interface

echo usercode "'''"
cat $BLNPY
echo "'''"
echo pymethoddef "'''"
grep '^{"' $BLNPY
echo "'''"
echo end python module pyfboxlib
