#
# $Id: GNUmakefile.tCArena,v 1.3 1998-08-21 18:06:08 car Exp $
#

#
# Set these to the appropriate place.
#
GUTHAMR_HOME = ..
COMP         = KCC
DIM          = 2
PRECISION    = DOUBLE
DEBUG        = TRUE

PBOXLIB_HOME = ..
include $(GUTHAMR_HOME)/mk/Make.defs

#LIBRARIES += -lbox$(optionsSuffix)

#
# Base name of each of the executables we want to build.
# I'm assuming that each of these is a stand-alone program,
# that simply needs to link against BoxLib.
#
EBASE = tCArena

CEXE_sources += tCArena.cpp CArena.cpp Utility.cpp BoxLib.cpp
CEXE_sources += aString.cpp Box.cpp IntVect.cpp

include $(GUTHAMR_HOME)/mk/Make.defs

all: $(executable)

include $(GUTHAMR_HOME)/mk/Make.rules


