#
# $Id: GNUmakefile.test,v 1.6 1998-09-25 17:57:13 lijewski Exp $
#

#
# Set these to the appropriate place.
#
GUTHAMR_HOME = ..
COMP         = KCC
DIM          = 2
PRECISION    = DOUBLE
DEBUG        = TRUE

PBOXLIB_HOME = ..
include $(GUTHAMR_HOME)/mk/Make.defs

LIBRARIES += -lbox$(optionsSuffix)

#
# Base name of each of the executables we want to build.
# I'm assuming that each of these is a stand-alone program,
# that simply needs to link against BoxLib.
#
_progs = tVisMF tDir t8BIT

all: $(addsuffix $(optionsSuffix).ex, $(_progs))

VPATH = ../pBoxLib_2:$(GUTHAMR_HOME)/lib

$(addsuffix $(optionsSuffix).ex, $(_progs)) \
   : %$(optionsSuffix).ex : %.cpp -lbox$(optionsSuffix)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@ $< $(libraries)
	$(RM) $@.o

#
# Run the tests ...
#
runtests : $(addsuffix $(optionsSuffix).ex, $(_progs))
        #
        # 
        #
	for f in $(filter-out tFABiofilt%,                 \
          $(addsuffix $(optionsSuffix).ex, $(_progs))); do \
          echo "====> Testing $$f ..."; echo; ./$$f; echo; \
        done

include $(GUTHAMR_HOME)/mk/Make.rules
