# BOXLIB_HOME defines the directory in which we will find all the BoxLib code
BOXLIB_HOME ?= ../../../..

# TOP defines the directory in which we will find Source, Exec, etc
TOP = ../..

# compilation options
COMP    = g++
FCOMP   = gfortran

USE_MPI   = TRUE
USE_UPCXX = TRUE

USE_OMP   = FALSE

PROFILE = FALSE

PRECISION = DOUBLE

DEBUG     = FALSE

DIM      = 3

Bpack := ./Make.package
Blocs := .

include ../Make.SMC
