
DEBUG     = TRUE

USE_MPI   = TRUE
USE_OMP   = FALSE
USE_MPI3  = FALSE

MEM_PROFILE  = FALSE
TINY_PROFILE = FALSE

COMP      = g++

DIM       = 3

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv


