# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?= ../../../../../

DEBUG     = FALSE
USE_MPI   = TRUE 
USE_OMP   = FALSE
DIM       = 3 
COMP      = gcc

USE_CUDA  = TRUE 
USE_HIP   = FALSE
USE_DPCPP = FALSE

Bpack   := ./Make.package
Blocs   := .

include ../../Make.HEAT
