
DEBUG     = TRUE
DEBUG     = FALSE

USE_MPI   = TRUE
USE_OMP   = FALSE
USE_MPI3  = FALSE

MEM_PROFILE  = FALSE
TINY_PROFILE = FALSE

COMP      = gnu

DIM       = 2
#DIM       = 3

USE_PARTICLES = TRUE
USE_F_INTERFACES = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv


