#!/bin/sh -f

# NOTE: the calling function (e.g. MAESTRO/write_job_info.f90) needs
# to allocate its strings to be the same size as those here.

# script to some information about the build environment
MAX_STRING_LENGTH=128
rm -f build_info.f90


BUILD_DATE=`date | cut -c 1-$MAX_STRING_LENGTH`
BUILD_DIR=`pwd | cut -c 1-$MAX_STRING_LENGTH`
BUILD_MACHINE=`uname -a | cut -c 1-$MAX_STRING_LENGTH`
MODULES=`echo $1 | cut -c 1-$MAX_STRING_LENGTH`

cat > build_info.f90 << EOF
module build_info_module

  implicit none

! the size of the strings is set to be the same as the size used in the
! cut in the shell script, so we don't go out of bounds

  character (len=$MAX_STRING_LENGTH), save :: build_date = &
"$BUILD_DATE"

  character (len=$MAX_STRING_LENGTH), save :: build_dir = &
"$BUILD_DIR"

  character (len=$MAX_STRING_LENGTH), save :: build_machine = &
"$BUILD_MACHINE"

  character (len=$MAX_STRING_LENGTH), save :: module_list = &
"$MODULES"

end module build_info_module

EOF



