#!/bin/sh -f

# script to some information about the build environment

rm -f build_info.f90


BUILD_DATE=`date | cut -c 1-255`
BUILD_DIR=`pwd | cut -c 1-255`
BUILD_MACHINE=`uname -a | cut -c 1-255`


cat > build_info.f90 << EOF
subroutine build_info(build_date, build_dir, build_machine)

  implicit none

! the size of the strings is set to be the same as the size used in the
! cut in the shell script, so we don't go out of bounds
  character (len=256) :: build_date, build_dir, build_machine

  build_date    = "$BUILD_DATE"
  build_dir     = "$BUILD_DIR"
  build_machine = "$BUILD_MACHINE"

  return
end subroutine build_info

EOF



