TINY_PROFILE = FALSE

DEBUG = FALSE
DIM=3
USE_MPI = TRUE
USE_OMP = FALSE

# set the HDF5 library directory (below is for Ubuntu 18.04)
HDF5_HOME   = /usr/lib/x86_64-linux-gnu/hdf5/openmpi
USE_HDF5 = FALSE



include ./Make.package
include ../Make.CNS

