AMREX_HOME = ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE

USE_SENSEI_INSITU = TRUE

Bpack   := ./Make.package
Blocs   := .

include ../Make.Adv
