AMREX_HOME ?= ../../amrex
PICSAR_HOME ?= ../../picsar

DEBUG	= FALSE
#DEBUG	= TRUE

DIM	= 3

COMP    = gcc

TINY_PROFILE = TRUE
TINY_PROFILE = FALSE

USE_MPI   = TRUE
USE_OMP   = TRUE

EBASE     = main

USE_PYTHON_MAIN = TRUE

WARPX_HOME := ..
include $(WARPX_HOME)/Source/Make.WarpX
