# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?= ../../../../../

DEBUG     = FALSE
USE_MPI   = FALSE 
USE_OMP   = FALSE
USE_HIP   = TRUE 
COMP      = hip
DIM       = 3 

Bpack   := ./Make.package
Blocs   := .

include ../../Make.HEAT
