AMREX_HOME = ../../

DEBUG	= FALSE

USE_MPI   = FALSE
USE_OMP   = FALSE

TINY_PROFILE = FALSE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
