#!/bin/bash

#SBATCH --job-name=homogeneous_plasma
#SBATCH --time=00:30:00
#SBATCH -n 64
#SBATCH --ntasks-per-node 32
#SBATCH --partition=debug
#SBATCH -C haswell
#SBATCH -e homogeneous_plasma.err
#SBATCH -o homogeneous_plasma.out

srun -n 64 ../main3d.gnu.TPROF.MPI.ex inputs
