#!/usr/bin/env bash
#
# Copyright 2021-2022 The AMReX Community
#
# Author: Axel Huebl
# License: BSD-3-Clause-LBNL

set -eu -o pipefail

# `man apt.conf`:
#   Number of retries to perform. If this is non-zero APT will retry
#   failed files the given number of times.
echo 'Acquire::Retries "3";' | sudo tee /etc/apt/apt.conf.d/80-retries

sudo apt-get -qqq update
sudo apt-get install -y \
    build-essential     \
    ca-certificates     \
    cmake               \
    environment-modules \
    gnupg               \
    pkg-config          \
    wget

curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | \
  sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | \
  sudo tee /etc/apt/sources.list.d/nvhpc.list
sudo apt-get update -y

# Avoid a CDN 404 for the "/amd64/./nvhpc-*.deb" URL generated by apt.
# Resolve the current versioned package through the unversioned meta-package.
NVHPC_METADATA=$(apt-cache show --no-all-versions nvhpc)
NVHPC_PACKAGE=$(sed -n 's/^Depends: \([^ ]*\).*/\1/p' <<< "${NVHPC_METADATA}")
NVHPC_METADATA=$(apt-cache show --no-all-versions "${NVHPC_PACKAGE}")
# Strip the leading "./" to produce the normalized CDN URL.
NVHPC_FILENAME=$(sed -n 's|^Filename: \./||p' <<< "${NVHPC_METADATA}")
NVHPC_SHA256=$(sed -n 's/^SHA256: //p' <<< "${NVHPC_METADATA}")
NVHPC_DEB="/tmp/${NVHPC_FILENAME##*/}"
# Use resumable HTTP/1.1 downloads to tolerate interrupted large transfers.
wget --continue --tries=5 --directory-prefix=/tmp \
    "https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64/${NVHPC_FILENAME}"
# Verify the manually downloaded package before installing it.
echo "${NVHPC_SHA256}  ${NVHPC_DEB}" | sha256sum --check -
sudo apt-get install -y --no-install-recommends "${NVHPC_DEB}"
rm -f "${NVHPC_DEB}"

# things should reside in /opt/nvidia/hpc_sdk now

# activation via:
#   source /etc/profile.d/modules.sh
#   module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc/23.3
