name: 🐧 Catalyst

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-insituvis
  cancel-in-progress: true

jobs:
  catalyst:
    name: Catalyst
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    env:
      CXX: g++
      CC: gcc
    container:
      image: cwetterernelson/catalyst:v2
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        cmake -S . -B build          \
            -DCMAKE_BUILD_TYPE=Debug \
            -DAMReX_ENABLE_TESTS=ON  \
            -DAMReX_FORTRAN=OFF      \
            -DAMReX_CATALYST=ON      \
            -DAMReX_CONDUIT=ON
    - name: Build
      run: |
        cmake --build build -j 2

