name: cmake

on: [push, pull_request]

jobs:
  # Build and install libamrex as AMReX CMake project
  library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: .github/workflows/cmake/dependencies.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/my-amrex
        make -j 2
        make install

  # Build and use AMReX via `add_subdirectory()`
  # Note - We build a pure C++ project here.
  #        In the future, this should compile without needing
  #        gfortran.
  subdirectory-CXX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: .github/workflows/cmake/dependencies.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ../Tutorials/Basic/HelloWorld_C
        make -j 2
        ./hello_amrex

  # Build and use AMReX via `add_subdirectory()`
  # Note - We build a mixed Fortran-C++ project here.
  subdirectory-Fortran-CXX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: .github/workflows/cmake/dependencies.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ../Tutorials/Particles/CellSortedParticles
        make -j 2
        make test
