name: codespell

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-codespell
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3-pip
          pip3 install --user --require-hashes \
              -r .github/workflows/requirements/codespell.txt

      - name: Run codespell
        run: codespell
