name: Style

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-style
  cancel-in-progress: true

jobs:
  tabs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Tabs
        run: .github/workflows/style/check_tabs.sh

  trailing_whitespaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trailing Whitespaces
        run: .github/workflows/style/check_trailing_whitespaces.sh

  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Doxygen
        run: |
          sudo apt-get install -y --no-install-recommends doxygen
          .github/workflows/style/doxygen.sh

  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate Zenodo Metadata
        uses: vsoch/zenodo-validator@main
        with:
          path: '.zenodo.json'
