name: Style

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-style
  cancel-in-progress: true

jobs:
  tabs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tabs
        run: .github/workflows/style/check_tabs.sh

  trailing_whitespaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trailing Whitespaces
        run: .github/workflows/style/check_trailing_whitespaces.sh
